// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || amd64p32 || arm || arm64 || loong64 || mips64le || mips64p32le || mipsle || ppc64le || riscv64

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type hyperionBpfDnsNameKey struct{ Name [255]uint8 }

type hyperionBpfFlowKey struct {
	SrcIp    uint32
	DstIp    uint32
	SrcPort  uint16
	DstPort  uint16
	Protocol uint8
	_        [3]byte
}

type hyperionBpfFlowValue struct {
	Packets   uint64
	Bytes     uint64
	FirstSeen uint64
	LastSeen  uint64
}

type hyperionBpfPolicyT struct {
	Signature [8]uint8
	SigLen    uint8
	Active    uint8
	Pad       [2]uint8
}

// loadHyperionBpf returns the embedded CollectionSpec for hyperionBpf.
func loadHyperionBpf() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_HyperionBpfBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load hyperionBpf: %w", err)
	}

	return spec, err
}

// loadHyperionBpfObjects loads hyperionBpf and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*hyperionBpfObjects
//	*hyperionBpfPrograms
//	*hyperionBpfMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadHyperionBpfObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadHyperionBpf()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// hyperionBpfSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type hyperionBpfSpecs struct {
	hyperionBpfProgramSpecs
	hyperionBpfMapSpecs
}

// hyperionBpfSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type hyperionBpfProgramSpecs struct {
	HyperionFilter *ebpf.ProgramSpec `ebpf:"hyperion_filter"`
}

// hyperionBpfMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type hyperionBpfMapSpecs struct {
	AlertRingbuf     *ebpf.MapSpec `ebpf:"alert_ringbuf"`
	BlocklistMap     *ebpf.MapSpec `ebpf:"blocklist_map"`
	DnsBlocklistMap  *ebpf.MapSpec `ebpf:"dns_blocklist_map"`
	FlowMap          *ebpf.MapSpec `ebpf:"flow_map"`
	PolicyMap        *ebpf.MapSpec `ebpf:"policy_map"`
	TelemetryRingbuf *ebpf.MapSpec `ebpf:"telemetry_ringbuf"`
}

// hyperionBpfObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadHyperionBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type hyperionBpfObjects struct {
	hyperionBpfPrograms
	hyperionBpfMaps
}

func (o *hyperionBpfObjects) Close() error {
	return _HyperionBpfClose(
		&o.hyperionBpfPrograms,
		&o.hyperionBpfMaps,
	)
}

// hyperionBpfMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadHyperionBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type hyperionBpfMaps struct {
	AlertRingbuf     *ebpf.Map `ebpf:"alert_ringbuf"`
	BlocklistMap     *ebpf.Map `ebpf:"blocklist_map"`
	DnsBlocklistMap  *ebpf.Map `ebpf:"dns_blocklist_map"`
	FlowMap          *ebpf.Map `ebpf:"flow_map"`
	PolicyMap        *ebpf.Map `ebpf:"policy_map"`
	TelemetryRingbuf *ebpf.Map `ebpf:"telemetry_ringbuf"`
}

func (m *hyperionBpfMaps) Close() error {
	return _HyperionBpfClose(
		m.AlertRingbuf,
		m.BlocklistMap,
		m.DnsBlocklistMap,
		m.FlowMap,
		m.PolicyMap,
		m.TelemetryRingbuf,
	)
}

// hyperionBpfPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadHyperionBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type hyperionBpfPrograms struct {
	HyperionFilter *ebpf.Program `ebpf:"hyperion_filter"`
}

func (p *hyperionBpfPrograms) Close() error {
	return _HyperionBpfClose(
		p.HyperionFilter,
	)
}

func _HyperionBpfClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed hyperionbpf_bpfel.o
var _HyperionBpfBytes []byte
