# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: shared/protocol.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'shared/protocol.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15shared/protocol.proto\x12\x05telos\"\'\n\x03\x41\x63k\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"u\n\x0bTaintReport\x12\x11\n\tsource_id\x18\x01 \x01(\t\x12\x0b\n\x03pid\x18\x02 \x01(\x05\x12\x0b\n\x03url\x18\x03 \x01(\t\x12 \n\x05level\x18\x04 \x01(\x0e\x32\x11.telos.TaintLevel\x12\x17\n\x0fpayload_preview\x18\x05 \x01(\t\"Z\n\rIntentRequest\x12\x11\n\tagent_pid\x18\x01 \x01(\x05\x12\x1d\n\x15natural_language_goal\x18\x02 \x01(\t\x12\x17\n\x0fplanned_actions\x18\x03 \x03(\t\"G\n\rIntentVerdict\x12\x0f\n\x07\x61llowed\x18\x01 \x01(\x08\x12\x0e\n\x06reason\x18\x02 \x01(\t\x12\x15\n\rpolicy_ttl_ms\x18\x03 \x01(\x03\"\x1a\n\x0bPolicyQuery\x12\x0b\n\x03pid\x18\x01 \x01(\x05\"g\n\x0bPolicyRules\x12,\n\x11max_allowed_taint\x18\x01 \x01(\x0e\x32\x11.telos.TaintLevel\x12\x13\n\x0b\x61llowed_ips\x18\x02 \x03(\t\x12\x15\n\rallowed_paths\x18\x03 \x03(\t*D\n\nTaintLevel\x12\t\n\x05\x43LEAN\x10\x00\x12\x07\n\x03LOW\x10\x01\x12\n\n\x06MEDIUM\x10\x02\x12\x08\n\x04HIGH\x10\x03\x12\x0c\n\x08\x43RITICAL\x10\x04\x32\xaf\x01\n\x0cTelosControl\x12-\n\x0bReportTaint\x12\x12.telos.TaintReport\x1a\n.telos.Ack\x12;\n\rDeclareIntent\x12\x14.telos.IntentRequest\x1a\x14.telos.IntentVerdict\x12\x33\n\tGetPolicy\x12\x12.telos.PolicyQuery\x1a\x12.telos.PolicyRulesB/Z-github.com/nevinshine/telos-runtime/shared/pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'shared.protocol_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z-github.com/nevinshine/telos-runtime/shared/pb'
  _globals['_TAINTLEVEL']._serialized_start=490
  _globals['_TAINTLEVEL']._serialized_end=558
  _globals['_ACK']._serialized_start=32
  _globals['_ACK']._serialized_end=71
  _globals['_TAINTREPORT']._serialized_start=73
  _globals['_TAINTREPORT']._serialized_end=190
  _globals['_INTENTREQUEST']._serialized_start=192
  _globals['_INTENTREQUEST']._serialized_end=282
  _globals['_INTENTVERDICT']._serialized_start=284
  _globals['_INTENTVERDICT']._serialized_end=355
  _globals['_POLICYQUERY']._serialized_start=357
  _globals['_POLICYQUERY']._serialized_end=383
  _globals['_POLICYRULES']._serialized_start=385
  _globals['_POLICYRULES']._serialized_end=488
  _globals['_TELOSCONTROL']._serialized_start=561
  _globals['_TELOSCONTROL']._serialized_end=736
# @@protoc_insertion_point(module_scope)
