// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: shared/protocol.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TaintLevel int32

const (
	TaintLevel_CLEAN    TaintLevel = 0
	TaintLevel_LOW      TaintLevel = 1 // Unverified Web
	TaintLevel_MEDIUM   TaintLevel = 2 // Hidden DOM Elements
	TaintLevel_HIGH     TaintLevel = 3 // Known Injection Signature
	TaintLevel_CRITICAL TaintLevel = 4 // Shellcode / Payload Detected
)

// Enum value maps for TaintLevel.
var (
	TaintLevel_name = map[int32]string{
		0: "CLEAN",
		1: "LOW",
		2: "MEDIUM",
		3: "HIGH",
		4: "CRITICAL",
	}
	TaintLevel_value = map[string]int32{
		"CLEAN":    0,
		"LOW":      1,
		"MEDIUM":   2,
		"HIGH":     3,
		"CRITICAL": 4,
	}
)

func (x TaintLevel) Enum() *TaintLevel {
	p := new(TaintLevel)
	*p = x
	return p
}

func (x TaintLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaintLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_shared_protocol_proto_enumTypes[0].Descriptor()
}

func (TaintLevel) Type() protoreflect.EnumType {
	return &file_shared_protocol_proto_enumTypes[0]
}

func (x TaintLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaintLevel.Descriptor instead.
func (TaintLevel) EnumDescriptor() ([]byte, []int) {
	return file_shared_protocol_proto_rawDescGZIP(), []int{0}
}

type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_shared_protocol_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_shared_protocol_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_shared_protocol_proto_rawDescGZIP(), []int{0}
}

func (x *Ack) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *Ack) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type TaintReport struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SourceId       string                 `protobuf:"bytes,1,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"` // e.g., "tab_ID_123"
	Pid            int32                  `protobuf:"varint,2,opt,name=pid,proto3" json:"pid,omitempty"`                          // Process ID of the browser
	Url            string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`                           // URL where taint was found
	Level          TaintLevel             `protobuf:"varint,4,opt,name=level,proto3,enum=telos.TaintLevel" json:"level,omitempty"`
	PayloadPreview string                 `protobuf:"bytes,5,opt,name=payload_preview,json=payloadPreview,proto3" json:"payload_preview,omitempty"` // First 64 chars of the hidden text
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TaintReport) Reset() {
	*x = TaintReport{}
	mi := &file_shared_protocol_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaintReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaintReport) ProtoMessage() {}

func (x *TaintReport) ProtoReflect() protoreflect.Message {
	mi := &file_shared_protocol_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaintReport.ProtoReflect.Descriptor instead.
func (*TaintReport) Descriptor() ([]byte, []int) {
	return file_shared_protocol_proto_rawDescGZIP(), []int{1}
}

func (x *TaintReport) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *TaintReport) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *TaintReport) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *TaintReport) GetLevel() TaintLevel {
	if x != nil {
		return x.Level
	}
	return TaintLevel_CLEAN
}

func (x *TaintReport) GetPayloadPreview() string {
	if x != nil {
		return x.PayloadPreview
	}
	return ""
}

type IntentRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	AgentPid            int32                  `protobuf:"varint,1,opt,name=agent_pid,json=agentPid,proto3" json:"agent_pid,omitempty"`
	NaturalLanguageGoal string                 `protobuf:"bytes,2,opt,name=natural_language_goal,json=naturalLanguageGoal,proto3" json:"natural_language_goal,omitempty"` // "I want to download invoices"
	PlannedActions      []string               `protobuf:"bytes,3,rep,name=planned_actions,json=plannedActions,proto3" json:"planned_actions,omitempty"`                  // ["connect:billing.com:443"]
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *IntentRequest) Reset() {
	*x = IntentRequest{}
	mi := &file_shared_protocol_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IntentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntentRequest) ProtoMessage() {}

func (x *IntentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_protocol_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntentRequest.ProtoReflect.Descriptor instead.
func (*IntentRequest) Descriptor() ([]byte, []int) {
	return file_shared_protocol_proto_rawDescGZIP(), []int{2}
}

func (x *IntentRequest) GetAgentPid() int32 {
	if x != nil {
		return x.AgentPid
	}
	return 0
}

func (x *IntentRequest) GetNaturalLanguageGoal() string {
	if x != nil {
		return x.NaturalLanguageGoal
	}
	return ""
}

func (x *IntentRequest) GetPlannedActions() []string {
	if x != nil {
		return x.PlannedActions
	}
	return nil
}

type IntentVerdict struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Allowed       bool                   `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	PolicyTtlMs   int64                  `protobuf:"varint,3,opt,name=policy_ttl_ms,json=policyTtlMs,proto3" json:"policy_ttl_ms,omitempty"` // How long the firewall stays open
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IntentVerdict) Reset() {
	*x = IntentVerdict{}
	mi := &file_shared_protocol_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IntentVerdict) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntentVerdict) ProtoMessage() {}

func (x *IntentVerdict) ProtoReflect() protoreflect.Message {
	mi := &file_shared_protocol_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntentVerdict.ProtoReflect.Descriptor instead.
func (*IntentVerdict) Descriptor() ([]byte, []int) {
	return file_shared_protocol_proto_rawDescGZIP(), []int{3}
}

func (x *IntentVerdict) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

func (x *IntentVerdict) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *IntentVerdict) GetPolicyTtlMs() int64 {
	if x != nil {
		return x.PolicyTtlMs
	}
	return 0
}

type PolicyQuery struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pid           int32                  `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PolicyQuery) Reset() {
	*x = PolicyQuery{}
	mi := &file_shared_protocol_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PolicyQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicyQuery) ProtoMessage() {}

func (x *PolicyQuery) ProtoReflect() protoreflect.Message {
	mi := &file_shared_protocol_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicyQuery.ProtoReflect.Descriptor instead.
func (*PolicyQuery) Descriptor() ([]byte, []int) {
	return file_shared_protocol_proto_rawDescGZIP(), []int{4}
}

func (x *PolicyQuery) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

type PolicyRules struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	MaxAllowedTaint TaintLevel             `protobuf:"varint,1,opt,name=max_allowed_taint,json=maxAllowedTaint,proto3,enum=telos.TaintLevel" json:"max_allowed_taint,omitempty"`
	AllowedIps      []string               `protobuf:"bytes,2,rep,name=allowed_ips,json=allowedIps,proto3" json:"allowed_ips,omitempty"`
	AllowedPaths    []string               `protobuf:"bytes,3,rep,name=allowed_paths,json=allowedPaths,proto3" json:"allowed_paths,omitempty"` // e.g., "/tmp/downloads/*"
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PolicyRules) Reset() {
	*x = PolicyRules{}
	mi := &file_shared_protocol_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PolicyRules) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicyRules) ProtoMessage() {}

func (x *PolicyRules) ProtoReflect() protoreflect.Message {
	mi := &file_shared_protocol_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicyRules.ProtoReflect.Descriptor instead.
func (*PolicyRules) Descriptor() ([]byte, []int) {
	return file_shared_protocol_proto_rawDescGZIP(), []int{5}
}

func (x *PolicyRules) GetMaxAllowedTaint() TaintLevel {
	if x != nil {
		return x.MaxAllowedTaint
	}
	return TaintLevel_CLEAN
}

func (x *PolicyRules) GetAllowedIps() []string {
	if x != nil {
		return x.AllowedIps
	}
	return nil
}

func (x *PolicyRules) GetAllowedPaths() []string {
	if x != nil {
		return x.AllowedPaths
	}
	return nil
}

var File_shared_protocol_proto protoreflect.FileDescriptor

const file_shared_protocol_proto_rawDesc = "" +
	"\n" +
	"\x15shared/protocol.proto\x12\x05telos\"9\n" +
	"\x03Ack\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xa0\x01\n" +
	"\vTaintReport\x12\x1b\n" +
	"\tsource_id\x18\x01 \x01(\tR\bsourceId\x12\x10\n" +
	"\x03pid\x18\x02 \x01(\x05R\x03pid\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\x12'\n" +
	"\x05level\x18\x04 \x01(\x0e2\x11.telos.TaintLevelR\x05level\x12'\n" +
	"\x0fpayload_preview\x18\x05 \x01(\tR\x0epayloadPreview\"\x89\x01\n" +
	"\rIntentRequest\x12\x1b\n" +
	"\tagent_pid\x18\x01 \x01(\x05R\bagentPid\x122\n" +
	"\x15natural_language_goal\x18\x02 \x01(\tR\x13naturalLanguageGoal\x12'\n" +
	"\x0fplanned_actions\x18\x03 \x03(\tR\x0eplannedActions\"e\n" +
	"\rIntentVerdict\x12\x18\n" +
	"\aallowed\x18\x01 \x01(\bR\aallowed\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12\"\n" +
	"\rpolicy_ttl_ms\x18\x03 \x01(\x03R\vpolicyTtlMs\"\x1f\n" +
	"\vPolicyQuery\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\x05R\x03pid\"\x92\x01\n" +
	"\vPolicyRules\x12=\n" +
	"\x11max_allowed_taint\x18\x01 \x01(\x0e2\x11.telos.TaintLevelR\x0fmaxAllowedTaint\x12\x1f\n" +
	"\vallowed_ips\x18\x02 \x03(\tR\n" +
	"allowedIps\x12#\n" +
	"\rallowed_paths\x18\x03 \x03(\tR\fallowedPaths*D\n" +
	"\n" +
	"TaintLevel\x12\t\n" +
	"\x05CLEAN\x10\x00\x12\a\n" +
	"\x03LOW\x10\x01\x12\n" +
	"\n" +
	"\x06MEDIUM\x10\x02\x12\b\n" +
	"\x04HIGH\x10\x03\x12\f\n" +
	"\bCRITICAL\x10\x042\xaf\x01\n" +
	"\fTelosControl\x12-\n" +
	"\vReportTaint\x12\x12.telos.TaintReport\x1a\n" +
	".telos.Ack\x12;\n" +
	"\rDeclareIntent\x12\x14.telos.IntentRequest\x1a\x14.telos.IntentVerdict\x123\n" +
	"\tGetPolicy\x12\x12.telos.PolicyQuery\x1a\x12.telos.PolicyRulesB/Z-github.com/nevinshine/telos-runtime/shared/pbb\x06proto3"

var (
	file_shared_protocol_proto_rawDescOnce sync.Once
	file_shared_protocol_proto_rawDescData []byte
)

func file_shared_protocol_proto_rawDescGZIP() []byte {
	file_shared_protocol_proto_rawDescOnce.Do(func() {
		file_shared_protocol_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shared_protocol_proto_rawDesc), len(file_shared_protocol_proto_rawDesc)))
	})
	return file_shared_protocol_proto_rawDescData
}

var file_shared_protocol_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_shared_protocol_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_shared_protocol_proto_goTypes = []any{
	(TaintLevel)(0),       // 0: telos.TaintLevel
	(*Ack)(nil),           // 1: telos.Ack
	(*TaintReport)(nil),   // 2: telos.TaintReport
	(*IntentRequest)(nil), // 3: telos.IntentRequest
	(*IntentVerdict)(nil), // 4: telos.IntentVerdict
	(*PolicyQuery)(nil),   // 5: telos.PolicyQuery
	(*PolicyRules)(nil),   // 6: telos.PolicyRules
}
var file_shared_protocol_proto_depIdxs = []int32{
	0, // 0: telos.TaintReport.level:type_name -> telos.TaintLevel
	0, // 1: telos.PolicyRules.max_allowed_taint:type_name -> telos.TaintLevel
	2, // 2: telos.TelosControl.ReportTaint:input_type -> telos.TaintReport
	3, // 3: telos.TelosControl.DeclareIntent:input_type -> telos.IntentRequest
	5, // 4: telos.TelosControl.GetPolicy:input_type -> telos.PolicyQuery
	1, // 5: telos.TelosControl.ReportTaint:output_type -> telos.Ack
	4, // 6: telos.TelosControl.DeclareIntent:output_type -> telos.IntentVerdict
	6, // 7: telos.TelosControl.GetPolicy:output_type -> telos.PolicyRules
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_shared_protocol_proto_init() }
func file_shared_protocol_proto_init() {
	if File_shared_protocol_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shared_protocol_proto_rawDesc), len(file_shared_protocol_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shared_protocol_proto_goTypes,
		DependencyIndexes: file_shared_protocol_proto_depIdxs,
		EnumInfos:         file_shared_protocol_proto_enumTypes,
		MessageInfos:      file_shared_protocol_proto_msgTypes,
	}.Build()
	File_shared_protocol_proto = out.File
	file_shared_protocol_proto_goTypes = nil
	file_shared_protocol_proto_depIdxs = nil
}
