# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from shared import protocol_pb2 as shared_dot_protocol__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in shared/protocol_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TelosControlStub(object):
    """The "Cortex" acts as the central server.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ReportTaint = channel.unary_unary(
                '/telos.TelosControl/ReportTaint',
                request_serializer=shared_dot_protocol__pb2.TaintReport.SerializeToString,
                response_deserializer=shared_dot_protocol__pb2.Ack.FromString,
                _registered_method=True)
        self.DeclareIntent = channel.unary_unary(
                '/telos.TelosControl/DeclareIntent',
                request_serializer=shared_dot_protocol__pb2.IntentRequest.SerializeToString,
                response_deserializer=shared_dot_protocol__pb2.IntentVerdict.FromString,
                _registered_method=True)
        self.GetPolicy = channel.unary_unary(
                '/telos.TelosControl/GetPolicy',
                request_serializer=shared_dot_protocol__pb2.PolicyQuery.SerializeToString,
                response_deserializer=shared_dot_protocol__pb2.PolicyRules.FromString,
                _registered_method=True)


class TelosControlServicer(object):
    """The "Cortex" acts as the central server.
    """

    def ReportTaint(self, request, context):
        """1. Browser Eye reports finding hidden text/taint
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeclareIntent(self, request, context):
        """2. Agent declares what it wants to do (Intent)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPolicy(self, request, context):
        """3. Daemons (Core/Edge) ask for latest rules
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TelosControlServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ReportTaint': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportTaint,
                    request_deserializer=shared_dot_protocol__pb2.TaintReport.FromString,
                    response_serializer=shared_dot_protocol__pb2.Ack.SerializeToString,
            ),
            'DeclareIntent': grpc.unary_unary_rpc_method_handler(
                    servicer.DeclareIntent,
                    request_deserializer=shared_dot_protocol__pb2.IntentRequest.FromString,
                    response_serializer=shared_dot_protocol__pb2.IntentVerdict.SerializeToString,
            ),
            'GetPolicy': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPolicy,
                    request_deserializer=shared_dot_protocol__pb2.PolicyQuery.FromString,
                    response_serializer=shared_dot_protocol__pb2.PolicyRules.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'telos.TelosControl', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('telos.TelosControl', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TelosControl(object):
    """The "Cortex" acts as the central server.
    """

    @staticmethod
    def ReportTaint(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/telos.TelosControl/ReportTaint',
            shared_dot_protocol__pb2.TaintReport.SerializeToString,
            shared_dot_protocol__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeclareIntent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/telos.TelosControl/DeclareIntent',
            shared_dot_protocol__pb2.IntentRequest.SerializeToString,
            shared_dot_protocol__pb2.IntentVerdict.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPolicy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/telos.TelosControl/GetPolicy',
            shared_dot_protocol__pb2.PolicyQuery.SerializeToString,
            shared_dot_protocol__pb2.PolicyRules.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
